name: diffpose
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pip
  - pytorch
  - torchvision
  - pip:
    - diffdrr==0.3.9
    - h5py
    - scikit-image
    - seaborn
    - pytorch-transformers
    - timm
    - torchmetrics
    - tqdm
    - beartype
    - jaxtyping
    - open3d
    - rtree
    - cupy-cuda12x
    - pyglet==1.5
    - nbdev
    - black
